name = "durable-object-experiments"
main = "src/index.tsx"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./public/", binding = "ASSETS" }

[ai]
binding = "AI"

[durable_objects]
bindings = [
  { name = "COUNTERS", class_name = "Counter" },
  { name = "WORLD", class_name = "World" },
  { name = "PLANTS", class_name = "Plant" },
  { name = "WEATHER", class_name = "Weather" },
  { name = "WEBSOCKET_HIBERNATION_SERVER", class_name = "WebSocketHibernationServer" },
  { name = "SQL_ITEMS", class_name = "SQLItems" },
  { name = "AI_EXAMPLE", class_name = "AIExample" },
  { name = "AI_CHAT_PARTICIPANT", class_name = "AIChatParticipant" },
  { name = "PARTY_SERVER_EXAMPLE", class_name = "PartyServerExample" }
]

[[migrations]]
tag = "v1"
new_classes = ["Counter", "World", "Plant", "Weather", "WebSocketHibernationServer", "PartyServerExample"]
new_sqlite_classes = ["SQLItems", "AIExample", "AIChatParticipant"]
